site_name: NextRNGBook Docs

theme:
  name: "material"
  features:
    - content.code.copy
  
plugins:
  - mkdocstrings
  
nav:
  - Home: index.md
  - Quick Start: quick_start.md
  - API Reference:
      - Overview: reference.md
      - dx_generator: dx_generator.md
  - Explanation: 
      - Team: team_and_contributor.md
  
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.arithmatex:
      generic: true
  - admonition
  - pymdownx.details
  - toc:
      toc_depth: 2

extra_javascript:
  - javascripts/mathjax.js